version: '3.1'

services:
  sJenkins:
    container_name: cJenkins
    image: jenkins/jenkins
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /C/docker-files/dd/compose-one/jenkins/data:/var/jenkins_home
