version: '3.1'

services:
  sPdb:
    container_name: cPdb
    image: postgres
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=hkn
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /C/docker-files/dd/compose-one/postgres/data:/var/lib/postgresql/data/pgdata
